repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_docs
        args:
          - '--args=--hide=modules'
          - '--args=--hide=providers'
      - id: terraform_tflint
        args:
          - '--args=--module'
      - id: terraform_fmt
      - id: terraform_validate

exclude: examples
